### ISSUE TITLE
Private key required

### ISSUE THREAD

**Issue by ivan-m** [Datanexus/postgresql#11]
Possibly more a documentation issue than anything else, but the ansible scripts assume a private key exists with a specified filename.

**Comment by ivan-m** [comment]
Should `existing_key.stat.exists` be used as a condition for the `generating public key from {{ region }}-postgresql-private-key.pem` task?

**Comment by ivan-m** [comment]
I think there's something wrong with the key logic in there, but as I'm not sure what the intent is I can't really debug it.

If I don't generate a key, I get an error like:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to inclu
de a variable that is undefined. The error was: 'dict object' has no attribute 'private_key'\n\nThe error appears to 
have been in '/Users/ivan/PartnerParts/datanexus-postgresql/aws/tasks/main.yml': line 129, column 5, but may\nbe else
where in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: saving {
{ region }}-{{ application }}\n    ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmiss
ing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n  
    - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}                              
```

But if I *do* create a key (`/usr/bin/ssh-keygen -f ap-southeast-2-postgresql-private-key.pem`) then I can't SSH into the instance.  Not sure if it's related, but if I go into the AWS console for EC2, select the created instance and click on the "Connect" button, it seems to think that the key I want is named `ap-southeast-2-postgresql.pem` (no `-private-key`).

**Comment by christopherkeller** [comment]
The SSH keys are auto generated by the AWS code (if necessary). You probably have a conflict in your account where the key exists on the server side but doesn't exist on the client side which makes bad things happen. Make sure you wipe all traces of postgresql keys from your current directory as well as the server and you are starting clean.
